### PR TITLE
Add support to Basic Authentication and permit disable of SSL certificate validation

### PR DESCRIPTION
**Pull request by geaaru**
Hi,

hereinafter, a new pull request for add support to basic authentication and permit to disable ssl certificate validation.

ty

--
geaaru

### CODE REVIEW

**Comment by geaaru** [comment]
If code is ok I will try to rebase to only one commit.
I wait for your feedback.
Thanks

**Comment by geaaru** [comment]
I try to explain what I understood of the class RepositoryConfigParser...
In 'write' function there is code that permit to write a configuration file related with repository id in input.
So, in my case I added these paremeters:
 - 'username' for HTTP Basic Authentication (a simple string)
 - 'password' for HTTP Basic Authentication (a simple string)
 - 'https_validate_cert' for Enable/Disable SSL Check of the certificate (a boolean value).

This means that a repository file could be like this:
[my-repos-id]
desc = xxx
enable = true (also hear is a boolean value that is saved as string on write function (enabled_str))
username = string1
password = string2
https_validate_cert = false

To maintains compatibility to current syntax I follow this algorithm:
1) if basic authentication is not present  doesn't add nothing (or only an empty string) for rows related with username and password. So these rows:

("", "username = %s" % username)[username],
("", "password = %s" % password)[password],

means that if username is None I use empty string ("") else I set complete row ("username = xxx" and/or "password = yyy").

2) if variable https_validate_cert is false I disable SSL certificate validation and I set complete string (https_validate_cert = false) in repository config file else I set an empty string ("") that means like current implementation enable SSL certificate validation. So these row:

"https_validate_cert" : ("https_validate_cert = false", "")[https_validate_cert]

means that if https_validate_cert variable (a boolean value) is true then I set an empty string ("") else I set string ("https_validate_cert = false).

Is related with write function of RepositoryConfigParser your doubt or to another function?

**Comment by lxnay** [comment]
Ok. I was simply debating the syntax you used.
It's just shocking to see that ("a", "b")[False/True] actually works.

That's fine, we can live with that.

Looks good to me, please squash everything into one commit.

On Wed, Jun 3, 2015 at 12:23 PM, geaaru <notifications@github.com> wrote:

> I try to explain what I understood of the class RepositoryConfigParser...
> In 'write' function there is code that permit to write a configuration
> file related with repository id in input.
> So, in my case I added these paremeters:
>
>    - 'username' for HTTP Basic Authentication (a simple string)
>    - 'password' for HTTP Basic Authentication (a simple string)
>    - 'https_validate_cert' for Enable/Disable SSL Check of the
>    certificate (a boolean value).
>
> This means that a repository file could be like this:
> [my-repos-id]
> desc = xxx
> enable = true (also hear is a boolean value that is saved as string on
> write function (enabled_str))
> username = string1
> password = string2
> https_validate_cert = false
>
> To maintains compatibility to current syntax I follow this algorithm:
> 1) if basic authentication is not present doesn't add nothing (or only an
> empty string) for rows related with username and password. So these rows:
>
> ("", "username = %s" % username)[username],
> ("", "password = %s" % password)[password],
>
> means that if username is None I use empty string ("") else I set complete
> row ("username = xxx" and/or "password = yyy").
>
> 2) if variable https_validate_cert is false I disable SSL certificate
> validation and I set complete string (https_validate_cert = false) in
> repository config file else I set an empty string ("") that means like
> current implementation enable SSL certificate validation. So these row:
>
> "https_validate_cert" : ("https_validate_cert = false",
> "")[https_validate_cert]
>
> means that if https_validate_cert variable (a boolean value) is true then
> I set an empty string ("") else I set string ("https_validate_cert = false).
>
> Is related with write function of RepositoryConfigParser your doubt or to
> another function?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sabayon/entropy/pull/13#issuecomment-108290042>.
>



-- 
Fabio Erculiani

**Comment by geaaru** [comment]
Done. I hope that I not add an error with squash. From a fast check to diff it seems all ok.
When you will merge my commit I will try soon if all it works.
I'm trying to do an ebuild with master git tree.
Is there a webpage where I can add some informations about this new feature?

**Comment by lxnay** [comment]
You can use wiki.sabayon.org

**Comment by geaaru** [comment]
I test entropy from master and it seems ok. Have you an idea about will be release a 298 version and/or if will be release a 298 release only with this patch?
Thanks

**Pull request merged**
