### PR TITLE
Revert "inject: fix store of content with utf-8 chars"

### PR DESCRIPTION
**Pull request by mudler**
Reverts Sabayon/entropy#52

### CODE REVIEW

**Comment by Enlik** [comment]
I was thinking of doing the same: a PR with revert.

Until a proper solution is figured out, it would be great to have master clean and experimental/WIP changes in forks or applied locally if necessary.


Also I'm tempted to revert it right away but (plural) your development in infra that I appreciate depends on it.


Are there plans to have it fixed promptly?

Otherwise I'm for reverting it purely for technical reasons:
- breaks tests (which slipped through automatic tests; tests runner was fixed after this),
- has unanswered questions regarding correctness:
  - Does it work with non-unicode paths, or handle them "gracefully enough," at least not worse than from was before?
  - Were other code paths checked: `equo install` worked, after all (modulo my comment [here](https://github.com/Sabayon/entropy/pull/52#issuecomment-410476712) [1])?
  - Was the effect of clients' database tested after the change?


[1] a possibly needed fix can be done later after some analysis; I'm not suggesting to do everything in one go, esp. given that trigger it are improbably, and can be likely detected server side before such package reaches client side

**Comment by geaaru** [comment]
I'm not agreed with revert but with additional changes to fix test and also this error that happens after creation of package puppet-agent:

```
Traceback (most recent call last):
  File "/usr/bin/equo", line 15, in <module>
    main()
  File "/usr/lib/entropy/client/solo/main.py", line 332, in main
    exit_st = func(*func_args)
  File "/usr/lib/entropy/client/solo/commands/command.py", line 435, in _call_shared
    return func(client)
  File "/usr/lib/entropy/client/solo/commands/upgrade.py", line 186, in _upgrade
    relaxed, multifetch)
  File "/usr/lib/entropy/client/solo/commands/upgrade.py", line 250, in _upgrade_action
    package_matches=update)
  File "/usr/lib/entropy/client/solo/commands/install.py", line 707, in _install_action
    exit_st = pkg.start()
  File "/usr/lib/entropy/lib/entropy/client/interfaces/package/actions/action.py", line 218, in start
    exit_st = self._run()
  File "/usr/lib/entropy/lib/entropy/client/interfaces/package/actions/install.py", line 260, in _run
    exit_st = method()
  File "/usr/lib/entropy/lib/entropy/client/interfaces/package/actions/install.py", line 1410, in _install_phase
    return self._install_phase_unlocked(inst_repo)
  File "/usr/lib/entropy/lib/entropy/client/interfaces/package/actions/install.py", line 1478, in _install_phase_unlocked
    inst_repo, installed_package_id)
  File "/usr/lib/entropy/lib/entropy/client/interfaces/package/actions/install.py", line 970, in _install_spm_package_unlocked
    spm_uid = spm.add_installed_package(self._meta)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 3149, in add_installed_package
    root, package_metadata)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 3255, in _add_installed_package_unlocked
    package_metadata)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 2997, in _create_contents_file_if_not_available
    root, pkg_dir, entropy_package_metadata)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 3057, in _create_contents_file_if_not_available_unlocked
    write_contents(content_meta, root, cont_f)
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 5410, in write_contents
    (entry_type, relative_filename, md5sum, mtime)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 96: ordinal not in range(128)

Frame write_contents in /usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py at line 5410
	            root_len = 0
	                   f = <closed file u'/var/db/pkg/app-admin/puppet-agent-5.5.4/CONTENTS', mode 'wb' at 0x7f69a087e810>
	          entry_type = 'obj'
	              md5sum = '601f1c03901a416643488f791f10c10e'
	            filename = '/opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/hocon-1.2.5/spec/fixtures/test_utils/resources/\xe1\x9a\xa0\xe1\x9b\x87\xe1\x9a\xbb.conf'
	          entry_data = ('obj', 1533394008, '601f1c03901a416643488f791f10c10e')
	                link = 'libxslt.so.1.1.29'
	   relative_filename = '/opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/hocon-1.2.5/spec/fixtures/test_utils/resources/\xe1\x9a\xa0\xe1\x9b\x87\xe1\x9a\xbb.conf'
	                root = '/'
	                line = u'obj /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/hocon-1.2.5/spec/fixtures/test_utils/resources/utf8.conf 601f1c03901a416643488f791f10c10e 1533394008\n'
	               mtime = 1533394008
```

Probably call to function to initialize sqlite session in utf8 must be done for every actions.

WDYT?

**Comment by mudler** [comment]
@geaaru Possibly, not sure. 

Also i'm not for reverting, as @Enlik says this is just for technical reasons, if the fix can't be provided in a shortly manner, better have a separate PR or branch with this change and later merge it back again once ready.

Is better to have a fixed master as it's easier also to spot bugs from other PR.

**Comment by Enlik** [comment]
Indeed (and thanks for merging): if there is a problem to be fixed, better to open an issue with some information:
- log as before,
- the exact command (steps to reproduce),
- whether it's unpatched Entropy or with the commit "inject: store (…)" (i.e. prior to the revert),
- what happens with unpatched Entropy (on a version from the repository on after this revert).

**Pull request merged**
