### PR TITLE
Improve equo generate subcommand for CI

### PR DESCRIPTION
**Pull request by geaaru**
Add option --yes-i-know-what-i-do-because-i-am-a-superhero
to generate sub command to avoid use of expect tool.

### CODE REVIEW

**Comment by Enlik** [comment]
OK from me if the option is changed to something less silly. I'd like a requirement to pass `--force` at least twice, but something else can work too. Either way, I think should be documented which this PR lacks.

**Comment by Enlik** [comment]
I forgot to add, documentation and help string should mention that it would replace the current packages DB (which I think is the case).

**Comment by geaaru** [comment]
@Enlik ok for documentation. I will add it.
I do not agree with `--force --force`. I prefer a single option for this or like other clients APIs an option "long"
@mudler wdyt ?

**Comment by mudler** [comment]
```--force --force``` might be misleading to some extent (did the doc had a typo, or ... the commands really want two --force? ), so I would be more inclined for a single flag. 

That doesn't implies that the proposed one is really 'standard' :) what about ```--not-ask```, ```--no-ask```, ```--no-interactive``` ?

**Comment by Enlik** [comment]
Correct me if I'm wrong: I think it's going to nuke the database.
If so then I think that something stronger than a var. is required; maybe also two flags, --force and --non-interactive? Or just one, to have standard behaviour, which should be also ok, but perhaps something more suggestive than --force. `--force-non-interactive`?

**Comment by Enlik** [comment]
s/more suggestive/less common/

**Comment by mudler** [comment]
> Correct me if I'm wrong: I think it's going to nuke the database.
> If so then I think that something stronger than a var. is required; maybe also two flags, --force and --non-interactive? Or just one, to have standard behaviour, which should be also ok, but perhaps something more suggestive than --force. `--force-non-interactive`?

Well, isn't that what this command is supposed to do? this PR is just to skip the interactive questions (that's why my --non-interactive) , not adding any nuke db logic which is already there

**Comment by Enlik** [comment]
Not necessarily literally "BIG LETTERS," otherwise we may have found a compromise. Now what will @geaaru say? :D

**Comment by geaaru** [comment]
I'm sad... super option ` --yes-i-know-what-i-do-because-i-am-a-superhero` is been rejected!! :)

However, ok for `--force-non-interactive` :+1: 

I will fix this tomorrow.

**Comment by Enlik** [comment]
Make it a default option.

**Comment by Enlik** [comment]
Just kidding. =)

**Pull request merged**
