### PR TITLE
Fix retrieve of kernel list when virtual/linux-binary contains RDEPEND with OR

### PR DESCRIPTION
**Pull request by geaaru**
I propose again my refactor with fix

### CODE REVIEW

**Comment by Enlik** [comment]
Why is the need of this "availables" mechanism?
Also, why user would want to maintain it? What kernels are available is defined by what is in repositories, not really some external file.

**Comment by geaaru** [comment]
About why use "availables" mechanism just an idea for:
1) to have a way for users to create a whitelist of only accepted kernels
2) to have a way for users for supply kernel list without virtual/linux-binary inclusions
3) to have a way that could be more easy to integrate with a new pm

However, currently, if `availables` directory is not present old logic is used. It's like a replacement enable on-demand.

**Comment by Enlik** [comment]
> About why use "availables" mechanism just an idea for:
> 
>     1. to have a way for users to create a whitelist of only accepted kernels

Why is this useful? People now just select a kernel they want, if they want to use a new version. With this new mechanism, they would need to, like, maintain a file and then *additionally* use kernel-switcher. It adds labour. Plus, this file would get outdated soon. Plus, if it's also supplied from a package, users' choice would be kind of overridden anyway… Or am I missing something?

>     2. to have a way for users for supply kernel list without virtual/linux-binary inclusions

What is an inclusion of virtual/linux-binary, and why is it bad?

>     3. to have a way that could be more easy to integrate with a new pm

No comment atm.

>     4. this file normally will be created manually but supply through a package

See reply to point 1.

>     5. this permit to share a new kernel that is hidden to normal users that use rigo or kernel-switch without mask it. Often masking generate problems on dependencies calculation

This sounds interesting. But a) why would it be hidden, b) in this case, shouldn't there new conf file just "unhide" hidden kernels, that is, couldn't it provide *additional kernel list* instead of *the authoritative source of kernels available for use*?
 
> However, currently, if `availables` directory is not present old logic is used. It's like a replacement enable on-demand.

But the intent is that it becomes available one day, shipped in a package or created by user (who may then forget about this file and then wonder why new kernels are not shown in kernel-switcher/rigo)…

**Comment by geaaru** [comment]
> Why is this useful? People now just select a kernel they want, if they want to use a new version. With this new mechanism, when they would like to use a different version, additional labour would be needed: first to update the file and then _additionally_ use kernel-switcher. Plus, this file would get outdated soon. Plus, if it's also supplied from a package, users' choice would be kind of overridden anyway… Or am I missing something?

This could be useful in an Enterprise use of Sabayon where you want to ensure that only a specific slot is returned. Example: 4.9.

About package update, file is under CONFIG_PROTECT directory that could be handled with equo conf update correctly.

> 
> > ```
> > 2. to have a way for users for supply kernel list without virtual/linux-binary inclusions
> > ```
> 
> What is an inclusion of virtual/linux-binary, and why is it bad?

Currently, kernel-switcher use statically the package virtual/linux-binary or virtual/linux-binary-lts for retrieve the list available. If an user push a vanilla kernel in his repos and/or custom kernel this could be used with kernel-switcher also if it's without PROVIDE (not set for development kernel for example) and you want enable installation of dev kernels.

> 
> > ```
> > 3. to have a way that could be more easy to integrate with a new pm
> > ```
> 
> No comment atm.
> 
> > ```
> > 4. this file normally will be created manually but supply through a package
> > ```
> 
> See reply to point 1.
> 
> > ```
> > 5. this permit to share a new kernel that is hidden to normal users that use rigo or kernel-switch without mask it. Often masking generate problems on dependencies calculation
> > ```
> 
> This sounds interesting. But a) why would it be hidden, b) in this case, shouldn't there new conf file just "unhide" hidden kernels, that is, couldn't it provide _additional kernel list_ instead of _the authoritative source of kernels available for use_?
> 
> > However, currently, if `availables` directory is not present old logic is used. It's like a replacement enable on-demand.
> 
> But the intent is that it becomes available one day, shipped in a package or created by user (who may then forget about this file and then wonder why new kernels are not shown in kernel-switcher/rigo)…

Why will it not available in kernel-switcher/rigo? This patch integrate a second way to share list of kernel available for both the tools. A way that will be documented in our wiki.

**Comment by Enlik** [comment]
"Enterprise" usage is only theoretical.

The argument of providing custom kernel package sounds more useful, and for that, a file that would provide ADDITIONAL kernels not "INSTEAD of the virtual/ ones" would do.

But I wonder, is it a real use case? Or is it just an idea of something possible?

Also: is there already a plan to provide this file? How? Don't get me wrong, reviews are for this kind of questions too.

> Why will it not available in kernel-switcher/rigo? This patch integrate a second way to share list of kernel available for both the tools. A way that will be documented in our wiki.

I meant:
- imagine that user creates this file with content "category/myshinykernel,"
- and from now on, kernel-switcher lists only "category/myshinykernel" and nothing else which is plain wrong.

**Comment by geaaru** [comment]
> "Enterprise" usage is only theoretical.

Currently, I have about 40 VM with Sabayon in production. I hope to have a day a Sabayon.org for support. :)

> 
> The argument of providing custom kernel package sounds more useful, and for that, a file that would provide ADDITIONAL kernels not "INSTEAD of the virtual/ ones" would do.
> 
> But I wonder, is it a real use case? Or is it just an idea of something possible?
> 
> Also: is there already a plan to provide this file? How? Don't get me wrong, reviews are for this kind of questions too.

We could create a package `sys-kernel/sabayon-specs` that push files under the right directory and it's an entropy deps. But for now, we could simply prepare that environment for this. The idea is to move kernel compilation away from chrooting so there are a lot of todo.

> 
> > Why will it not available in kernel-switcher/rigo? This patch integrate a second way to share list of kernel available for both the tools. A way that will be documented in our wiki.
> 
> I meant:
> 
> * imagine that user creates this file with content "category/myshinykernel,"
> * and from now on, kernel-switcher lists only "category/myshinykernel" and nothing else which is plain wrong.

If a user write a kernel that doesn't exist is a user error. It's like said, if a user edits entropy code, change it and then it's broken. However, a user could maintain our files and add a specific file his kernel all works correctly.

Example:
```
$# ls /etc/kernel/availables/
sabayon-lts sabayon userkernel
$# cat /etc/kernel/availables/userkernel
category/myshinykernel
$# kernel-switch list -q -v
sys-kernel/linux-sabayon-4.4.200
..
category/myshinykernel
```

**Comment by geaaru** [comment]
Probably it's less integrate with Gentoo stuff but it's KISS, IMHO.

**Comment by Enlik** [comment]
I simply fail to see a reason to have it. It would be just additional maintenance burden (not just kernel bump but also a file with redundant information).

I fail to see practical application of this.

The only (although without real world example) useful would to be allow adding extra kernels, that don't use the virtual, but for this I propose that the files would contain "additional kernels" which seems to be rejected here.

So a definitive -2 from me but it's not gerrit, collect some pluses from others instead. :/

**Comment by mudler** [comment]
I don't dislike the idea. Actually I like it because lets make it very explicit what's provided as options and gives a direct mapping: what we clearly state is what the user sees, and nothing is left for elaboration by a logic that doesn't speak for itself (aka hard to get for everybody that have to maintan it). 

I'm against the fact that it's given as the default way to choose for kernels right immediately introducing the feature.

I think we should first introduce the feature, and start using it, later on we can mark it as default if successful, otherwise not.

It makes it clear for everybody (even in a packagable way) what the user are seeing, so a +1, but with the nit that phrasing, and ordering must be inverted (first old way, and we add on top)

**Comment by geaaru** [comment]
Done. Now, `/etc/kernels/availables` dir is used for append additional kernels to the list of the kernel available.

**Comment by geaaru** [comment]
I split the commit so it's easier to execute a revert. I move ahead and I bump a new release.

**Pull request merged**
