### PR TITLE
lib/entropy/tools.py: add support for RISCV ELF class

### PR DESCRIPTION
**Pull request by gktrk**
spmsync freaks out on a RISC-V toolchain built using crossdev. The issue is a bit complicated in that current pax-utils also does not recognize riscv and returns "UNKNOWN_TYPE", which gets truncated to "OWN_TYPE" by portage. I just submitted a patch to fix this in pax-utils. Once scanelf starts recognizing RISCV, entropy needs to be updated as well. Note that only the 64-bit RISCV is currently supported in Gentoo.

### CODE REVIEW

**Comment by Enlik** [comment]
Is it really needed? I've seen that the first field, as returned by patched and unpatched scanelf says (the "%M" format) `ELFCLASS64` which is already handled. I used a RISC-V binary from unofficial (?) Alpine Linux port.

**Comment by gktrk** [comment]
Steps to reproduce:

1. Download https://github.com/gentoo/pax-utils/commit/b624f3ad5c41dfd246f5b31f02e843874850b49d.patch and drop it under `/etc/portage/patches/app-misc/pax-utils/v1-0001-Add-RISC-V-to-the-list-of-architectures-in-ELF.patch`
2. Emerge pax-utils-1.2.5. Make sure the patch is applied:
```console
>>> Preparing source in /var/tmp/portage/app-misc/pax-utils-1.2.5/work/pax-utils-1.2.5 ...
 * Applying v1-0001-Add-RISC-V-to-the-list-of-architectures-in-ELF.patch ...                                                     [ ok ]
 * User patches applied.
```
3. Emerge the live version of crossdev:
```console
emerge -av =sys-devel/crossdev-99999999
```
4. Build a rv64 toolchain (might want to adjust the argument to `--ov-output` on your system):
```console
crossdev --binutils 2.34 --gcc 9.3.0 --kernel 5.4 --libc 2.30-r6 -P "--verbose" --show-fail-log --ov-output /var/lib/overlay/cross/ --abis lp64d -s4 --target riscv64-unknown-linux-gnu
```
5. Try to make entropy happy:
```console
equo rescue spmsync
╠  @@ These packages were added:
╠     # cross-riscv64-unknown-linux-gnu/binutils-2.34
╠     # cross-riscv64-unknown-linux-gnu/linux-headers-5.4
╠     # cross-riscv64-unknown-linux-gnu/gcc-9.3.0
╠     # cross-riscv64-unknown-linux-gnu/glibc-2.30-r6
╠  +++  (1/4) cross-riscv64-unknown-linux-gnu/binutils-2.34
╠  +++  (2/4) cross-riscv64-unknown-linux-gnu/linux-headers-5.4
╠  +++  (3/4) cross-riscv64-unknown-linux-gnu/gcc-9.3.0
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/_entropy/solo/commands/rescue.py", line 768, in _spmsync
    data = spm.extract_package_metadata(tmp_path)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1574, in extract_package_metadata
    needed_elf_file)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 4779, in _extract_pkg_metadata_needed_libs_elf_2
    elfclass = entropy.tools.elf_class_strtoint(elfclass_str)
  File "/usr/lib64/python3.6/site-packages/entropy/tools.py", line 2631, in elf_class_strtoint
    raise ValueError('unsupported %s' % (elf_class_str,))
ValueError: unsupported RISCV
☛  @@ cross-riscv64-unknown-linux-gnu/gcc-9.3.0, Metadata generation error: unsupported RISCV
╠  +++  (4/4) cross-riscv64-unknown-linux-gnu/glibc-2.30-r6
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/_entropy/solo/commands/rescue.py", line 768, in _spmsync
    data = spm.extract_package_metadata(tmp_path)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1574, in extract_package_metadata
    needed_elf_file)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 4779, in _extract_pkg_metadata_needed_libs_elf_2
    elfclass = entropy.tools.elf_class_strtoint(elfclass_str)
  File "/usr/lib64/python3.6/site-packages/entropy/tools.py", line 2631, in elf_class_strtoint
    raise ValueError('unsupported %s' % (elf_class_str,))
ValueError: unsupported RISCV
☛  @@ cross-riscv64-unknown-linux-gnu/glibc-2.30-r6, Metadata generation error: unsupported RISCV
╠  @@ Update complete
```
6. Entropy is not happy:
```console
# equo rescue spmsync
╠  @@ These packages were added:
╠     # cross-riscv64-unknown-linux-gnu/gcc-9.3.0
╠     # cross-riscv64-unknown-linux-gnu/glibc-2.30-r6
╠  +++  (1/2) cross-riscv64-unknown-linux-gnu/gcc-9.3.0
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/_entropy/solo/commands/rescue.py", line 768, in _spmsync
    data = spm.extract_package_metadata(tmp_path)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1574, in extract_package_metadata
    needed_elf_file)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 4779, in _extract_pkg_metadata_needed_libs_elf_2
    elfclass = entropy.tools.elf_class_strtoint(elfclass_str)
  File "/usr/lib64/python3.6/site-packages/entropy/tools.py", line 2631, in elf_class_strtoint
    raise ValueError('unsupported %s' % (elf_class_str,))
ValueError: unsupported RISCV
☛  @@ cross-riscv64-unknown-linux-gnu/gcc-9.3.0, Metadata generation error: unsupported RISCV
╠  +++  (2/2) cross-riscv64-unknown-linux-gnu/glibc-2.30-r6
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/_entropy/solo/commands/rescue.py", line 768, in _spmsync
    data = spm.extract_package_metadata(tmp_path)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1574, in extract_package_metadata
    needed_elf_file)
  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 4779, in _extract_pkg_metadata_needed_libs_elf_2
    elfclass = entropy.tools.elf_class_strtoint(elfclass_str)
  File "/usr/lib64/python3.6/site-packages/entropy/tools.py", line 2631, in elf_class_strtoint
    raise ValueError('unsupported %s' % (elf_class_str,))
ValueError: unsupported RISCV
☛  @@ cross-riscv64-unknown-linux-gnu/glibc-2.30-r6, Metadata generation error: unsupported RISCV
╠  @@ Update complete
```

**Comment by gktrk** [comment]
The patch makes entropy happy again:
```console
# equo rescue spmsync
╠  @@ These packages were added:
╠     # cross-riscv64-unknown-linux-gnu/gcc-9.3.0
╠     # cross-riscv64-unknown-linux-gnu/glibc-2.30-r6
╠  +++  (1/2) cross-riscv64-unknown-linux-gnu/gcc-9.3.0
╠  +++  (2/2) cross-riscv64-unknown-linux-gnu/glibc-2.30-r6
╠  @@ Update complete
```

**Comment by Enlik** [comment]
Could you please share output of:
`scanelf -qF "%M;%S;%r;%n" some-riscv-binary`? I'm not saying what you showed is wrong, but I'd like to understand what's going on.

**Comment by Enlik** [comment]
Oh, I missed a code path that uses `entropy.tools.elf_class_strtoint()`. I'll check again, sorry.

**Comment by Enlik** [comment]
> and returns "UNKNOWN_TYPE", which gets truncated to "OWN_TYPE" by portage

actually to `NOWN_TYPE` ;)

Merging, thanks.

**Pull request merged**
