### PR TITLE
[entropy-client] Add support to Basic Authentication and permit disable of SSL certificat...

### PR DESCRIPTION
**Pull request by geaaru**
Hi,

as describe on ml , my pull request related with:
- add support to basic authentication
- add support to permit disable of ssl certificate validation on https

Thank you.
geaaru

### CODE REVIEW

**Comment by geaaru** [comment]
Hi lxnay,

I apply changes related with your suggestions on my fork.

Thank you very much for fast reply.

**Comment by lxnay** [comment]
Please squash the two commits together (and make a single one)

**Comment by geaaru** [comment]
Hi lxnay,

sorry but I have few experience on git rebase / pull request / projects integrations . I revert my commit before see that exists rebase function on git. So I execute a git cherry-pick with a merge of all commits.
Can you merge pull request only with last commit ?

**Comment by lxnay** [comment]
Please send a new pull request with just the commits you want to merge.

On Fri, May 8, 2015 at 10:26 AM, geaaru <notifications@github.com> wrote:

> Hi lxnay,
>
> sorry but I have few experience on git rebase / pull request / projects
> integrations . I revert my commit before see that exists rebase function on
> git. So I execute a git cherry-pick with a merge of all commits.
> Can you merge pull request only with last commit ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sabayon/entropy/pull/12#issuecomment-100171865>.
>



-- 
Fabio Erculiani

**Comment by geaaru** [comment]
Well,
i try to open a new pull request.

Thanks.

**Pull request closed without merging**
